--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzli/JobUINa
build-by-default: true
branches:
- main
projects:
  JobUINa:
    path: ""
    icon: icon.png
    libs:
  - src: jojoe77777/FormUI/libsFormUI
...
